// Mocks generated by Mockito 5.4.6 from annotations
// in thunder/test/features/chat/domain/usecases/add_reaction_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:thunder/core/errors/failures.dart' as _i2;
import 'package:thunder/features/chat/domain/entities/chat_entity.dart' as _i6;
import 'package:thunder/features/chat/domain/entities/message_entity.dart'
    as _i7;
import 'package:thunder/features/chat/domain/repositories/chat_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i3.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getChatId(String? userA, String? userB) =>
      (super.noSuchMethod(
            Invocation.method(#getChatId, [userA, userB]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getChatId, [userA, userB]),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.Either<_i2.Failure, _i6.ChatEntity?>> getChatById(
    String? chatId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChatById, [chatId]),
            returnValue:
                _i5.Future<_i2.Either<_i2.Failure, _i6.ChatEntity?>>.value(
                  _FakeEither_0<_i2.Failure, _i6.ChatEntity?>(
                    this,
                    Invocation.method(#getChatById, [chatId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, _i6.ChatEntity?>>);

  @override
  _i5.Stream<_i6.ChatEntity?> getChatStream(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatStream, [chatId]),
            returnValue: _i5.Stream<_i6.ChatEntity?>.empty(),
          )
          as _i5.Stream<_i6.ChatEntity?>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, _i6.ChatEntity>> getOrCreatePrivateChat(
    String? userA,
    String? userB,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreatePrivateChat, [userA, userB]),
            returnValue:
                _i5.Future<_i2.Either<_i2.Failure, _i6.ChatEntity>>.value(
                  _FakeEither_0<_i2.Failure, _i6.ChatEntity>(
                    this,
                    Invocation.method(#getOrCreatePrivateChat, [userA, userB]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, _i6.ChatEntity>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, _i6.ChatEntity>> createGroupChat({
    required String? name,
    required String? createdBy,
    required List<String>? participants,
    String? description,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGroupChat, [], {
              #name: name,
              #createdBy: createdBy,
              #participants: participants,
              #description: description,
              #photoUrl: photoUrl,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i2.Failure, _i6.ChatEntity>>.value(
                  _FakeEither_0<_i2.Failure, _i6.ChatEntity>(
                    this,
                    Invocation.method(#createGroupChat, [], {
                      #name: name,
                      #createdBy: createdBy,
                      #participants: participants,
                      #description: description,
                      #photoUrl: photoUrl,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, _i6.ChatEntity>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>> sendMessage({
    required String? chatId,
    required String? senderId,
    required String? senderName,
    String? senderPhotoUrl,
    String? text,
    _i7.MessageType? type = _i7.MessageType.text,
    String? imageUrl,
    String? videoUrl,
    String? audioUrl,
    String? fileUrl,
    String? fileName,
    int? fileSize,
    String? gifUrl,
    String? stickerUrl,
    Map<String, dynamic>? location,
    Map<String, dynamic>? contact,
    String? replyToMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatId: chatId,
              #senderId: senderId,
              #senderName: senderName,
              #senderPhotoUrl: senderPhotoUrl,
              #text: text,
              #type: type,
              #imageUrl: imageUrl,
              #videoUrl: videoUrl,
              #audioUrl: audioUrl,
              #fileUrl: fileUrl,
              #fileName: fileName,
              #fileSize: fileSize,
              #gifUrl: gifUrl,
              #stickerUrl: stickerUrl,
              #location: location,
              #contact: contact,
              #replyToMessageId: replyToMessageId,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>>.value(
                  _FakeEither_0<_i2.Failure, _i7.MessageEntity>(
                    this,
                    Invocation.method(#sendMessage, [], {
                      #chatId: chatId,
                      #senderId: senderId,
                      #senderName: senderName,
                      #senderPhotoUrl: senderPhotoUrl,
                      #text: text,
                      #type: type,
                      #imageUrl: imageUrl,
                      #videoUrl: videoUrl,
                      #audioUrl: audioUrl,
                      #fileUrl: fileUrl,
                      #fileName: fileName,
                      #fileSize: fileSize,
                      #gifUrl: gifUrl,
                      #stickerUrl: stickerUrl,
                      #location: location,
                      #contact: contact,
                      #replyToMessageId: replyToMessageId,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>>);

  @override
  _i5.Stream<List<_i7.MessageEntity>> getMessagesStream(
    String? chatId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesStream, [chatId], {#limit: limit}),
            returnValue: _i5.Stream<List<_i7.MessageEntity>>.empty(),
          )
          as _i5.Stream<List<_i7.MessageEntity>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, List<_i7.MessageEntity>>>
  loadOlderMessages(
    String? chatId,
    DateTime? lastMessageTime, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadOlderMessages,
              [chatId, lastMessageTime],
              {#limit: limit},
            ),
            returnValue:
                _i5.Future<
                  _i2.Either<_i2.Failure, List<_i7.MessageEntity>>
                >.value(
                  _FakeEither_0<_i2.Failure, List<_i7.MessageEntity>>(
                    this,
                    Invocation.method(
                      #loadOlderMessages,
                      [chatId, lastMessageTime],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, List<_i7.MessageEntity>>>);

  @override
  _i5.Stream<List<_i6.ChatEntity>> getUserChats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserChats, [userId]),
            returnValue: _i5.Stream<List<_i6.ChatEntity>>.empty(),
          )
          as _i5.Stream<List<_i6.ChatEntity>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> markMessageAsRead(
    String? messageId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageAsRead, [messageId, userId]),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#markMessageAsRead, [messageId, userId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> deleteMessage(
    String? messageId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId, userId]),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#deleteMessage, [messageId, userId]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> editMessage(
    String? messageId,
    String? newText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editMessage, [messageId, newText]),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#editMessage, [messageId, newText]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> updateTypingStatus(
    String? chatId,
    String? userId,
    bool? isTyping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTypingStatus, [chatId, userId, isTyping]),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#updateTypingStatus, [
                  chatId,
                  userId,
                  isTyping,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> addReaction(
    String? messageId,
    String? userId,
    String? emoji,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addReaction, [messageId, userId, emoji]),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#addReaction, [messageId, userId, emoji]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> removeReaction(
    String? messageId,
    String? userId,
    String? emoji,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeReaction, [messageId, userId, emoji]),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#removeReaction, [messageId, userId, emoji]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>> sendVoiceMessage({
    required String? chatId,
    required String? senderId,
    required String? senderName,
    String? senderPhotoUrl,
    required String? audioUrl,
    required Duration? duration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendVoiceMessage, [], {
              #chatId: chatId,
              #senderId: senderId,
              #senderName: senderName,
              #senderPhotoUrl: senderPhotoUrl,
              #audioUrl: audioUrl,
              #duration: duration,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>>.value(
                  _FakeEither_0<_i2.Failure, _i7.MessageEntity>(
                    this,
                    Invocation.method(#sendVoiceMessage, [], {
                      #chatId: chatId,
                      #senderId: senderId,
                      #senderName: senderName,
                      #senderPhotoUrl: senderPhotoUrl,
                      #audioUrl: audioUrl,
                      #duration: duration,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>> sendFileMessage({
    required String? chatId,
    required String? senderId,
    required String? senderName,
    String? senderPhotoUrl,
    required String? fileUrl,
    required String? fileName,
    required int? fileSize,
    String? fileExtension,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendFileMessage, [], {
              #chatId: chatId,
              #senderId: senderId,
              #senderName: senderName,
              #senderPhotoUrl: senderPhotoUrl,
              #fileUrl: fileUrl,
              #fileName: fileName,
              #fileSize: fileSize,
              #fileExtension: fileExtension,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>>.value(
                  _FakeEither_0<_i2.Failure, _i7.MessageEntity>(
                    this,
                    Invocation.method(#sendFileMessage, [], {
                      #chatId: chatId,
                      #senderId: senderId,
                      #senderName: senderName,
                      #senderPhotoUrl: senderPhotoUrl,
                      #fileUrl: fileUrl,
                      #fileName: fileName,
                      #fileSize: fileSize,
                      #fileExtension: fileExtension,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>> forwardMessage({
    required _i7.MessageEntity? originalMessage,
    required String? targetChatId,
    required String? senderId,
    required String? senderName,
    String? senderPhotoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forwardMessage, [], {
              #originalMessage: originalMessage,
              #targetChatId: targetChatId,
              #senderId: senderId,
              #senderName: senderName,
              #senderPhotoUrl: senderPhotoUrl,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>>.value(
                  _FakeEither_0<_i2.Failure, _i7.MessageEntity>(
                    this,
                    Invocation.method(#forwardMessage, [], {
                      #originalMessage: originalMessage,
                      #targetChatId: targetChatId,
                      #senderId: senderId,
                      #senderName: senderName,
                      #senderPhotoUrl: senderPhotoUrl,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, _i7.MessageEntity>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, List<_i7.MessageEntity>>> searchMessages(
    String? chatId,
    String? query, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchMessages,
              [chatId, query],
              {#limit: limit},
            ),
            returnValue:
                _i5.Future<
                  _i2.Either<_i2.Failure, List<_i7.MessageEntity>>
                >.value(
                  _FakeEither_0<_i2.Failure, List<_i7.MessageEntity>>(
                    this,
                    Invocation.method(
                      #searchMessages,
                      [chatId, query],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, List<_i7.MessageEntity>>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, List<_i7.MessageEntity>>>
  searchAllMessages(String? userId, String? query, {int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchAllMessages,
              [userId, query],
              {#limit: limit},
            ),
            returnValue:
                _i5.Future<
                  _i2.Either<_i2.Failure, List<_i7.MessageEntity>>
                >.value(
                  _FakeEither_0<_i2.Failure, List<_i7.MessageEntity>>(
                    this,
                    Invocation.method(
                      #searchAllMessages,
                      [userId, query],
                      {#limit: limit},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, List<_i7.MessageEntity>>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, String>> uploadVoiceMessage(
    String? audioFilePath, {
    required String? chatId,
    required String? senderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadVoiceMessage,
              [audioFilePath],
              {#chatId: chatId, #senderId: senderId},
            ),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, String>>.value(
              _FakeEither_0<_i2.Failure, String>(
                this,
                Invocation.method(
                  #uploadVoiceMessage,
                  [audioFilePath],
                  {#chatId: chatId, #senderId: senderId},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, String>> uploadFileMessage(
    String? filePath,
    String? fileName, {
    required String? chatId,
    required String? senderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFileMessage,
              [filePath, fileName],
              {#chatId: chatId, #senderId: senderId},
            ),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, String>>.value(
              _FakeEither_0<_i2.Failure, String>(
                this,
                Invocation.method(
                  #uploadFileMessage,
                  [filePath, fileName],
                  {#chatId: chatId, #senderId: senderId},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, String>> uploadChatMedia(
    String? filePath,
    String? storagePath, {
    String? contentType,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadChatMedia,
              [filePath, storagePath],
              {#contentType: contentType, #onProgress: onProgress},
            ),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, String>>.value(
              _FakeEither_0<_i2.Failure, String>(
                this,
                Invocation.method(
                  #uploadChatMedia,
                  [filePath, storagePath],
                  {#contentType: contentType, #onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> updateGroupInfo({
    required String? chatId,
    String? name,
    String? description,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateGroupInfo, [], {
              #chatId: chatId,
              #name: name,
              #description: description,
              #photoUrl: photoUrl,
            }),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#updateGroupInfo, [], {
                  #chatId: chatId,
                  #name: name,
                  #description: description,
                  #photoUrl: photoUrl,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> addAdmin({
    required String? chatId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAdmin, [], {
              #chatId: chatId,
              #userId: userId,
            }),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#addAdmin, [], {
                  #chatId: chatId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> removeAdmin({
    required String? chatId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeAdmin, [], {
              #chatId: chatId,
              #userId: userId,
            }),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#removeAdmin, [], {
                  #chatId: chatId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> muteChat({
    required String? chatId,
    required String? userId,
    DateTime? muteUntil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#muteChat, [], {
              #chatId: chatId,
              #userId: userId,
              #muteUntil: muteUntil,
            }),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#muteChat, [], {
                  #chatId: chatId,
                  #userId: userId,
                  #muteUntil: muteUntil,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i2.Failure, void>> unmuteChat({
    required String? chatId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unmuteChat, [], {
              #chatId: chatId,
              #userId: userId,
            }),
            returnValue: _i5.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#unmuteChat, [], {
                  #chatId: chatId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i2.Failure, void>>);
}
