// Mocks generated by Mockito 5.4.6 from annotations
// in thunder/test/features/event/data/repositories/event_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:thunder/features/event/data/datasources/event_remote_data_source.dart'
    as _i2;
import 'package:thunder/features/event/data/models/event_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EventRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRemoteDataSource extends _i1.Mock
    implements _i2.EventRemoteDataSource {
  MockEventRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addEvent(_i4.EventModel? event) =>
      (super.noSuchMethod(
            Invocation.method(#addEvent, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.EventModel>> getEventsStream() =>
      (super.noSuchMethod(
            Invocation.method(#getEventsStream, []),
            returnValue: _i3.Stream<List<_i4.EventModel>>.empty(),
          )
          as _i3.Stream<List<_i4.EventModel>>);

  @override
  _i3.Stream<List<_i4.EventModel>> getUserEventsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserEventsStream, [userId]),
            returnValue: _i3.Stream<List<_i4.EventModel>>.empty(),
          )
          as _i3.Stream<List<_i4.EventModel>>);

  @override
  _i3.Future<List<_i4.EventModel>> fetchNextEvents({
    DateTime? startAfter,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNextEvents, [], {
              #startAfter: startAfter,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.EventModel>>.value(
              <_i4.EventModel>[],
            ),
          )
          as _i3.Future<List<_i4.EventModel>>);

  @override
  _i3.Future<void> updateEvent(_i4.EventModel? event) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvent, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [eventId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> joinEvent(String? eventId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#joinEvent, [eventId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> leaveEvent(String? eventId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveEvent, [eventId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendJoinRequest(String? eventId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#sendJoinRequest, [eventId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> approveJoinRequest(String? eventId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#approveJoinRequest, [eventId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> rejectJoinRequest(String? eventId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectJoinRequest, [eventId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelJoinRequest(String? eventId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelJoinRequest, [eventId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeParticipant(String? eventId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeParticipant, [eventId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelEvent(String? eventId, String? cancellationReason) =>
      (super.noSuchMethod(
            Invocation.method(#cancelEvent, [eventId, cancellationReason]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> uploadEventCoverPhoto(
    _i5.File? photoFile, {
    String? eventId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadEventCoverPhoto,
              [photoFile],
              {#eventId: eventId},
            ),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadEventCoverPhoto,
                  [photoFile],
                  {#eventId: eventId},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> uploadEventPhoto(_i5.File? photoFile, String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#uploadEventPhoto, [photoFile, eventId]),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#uploadEventPhoto, [photoFile, eventId]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Stream<_i4.EventModel?> getEventStream(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventStream, [eventId]),
            returnValue: _i3.Stream<_i4.EventModel?>.empty(),
          )
          as _i3.Stream<_i4.EventModel?>);

  @override
  _i3.Stream<List<Map<String, dynamic>>> getEventCommentsStream(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventCommentsStream, [eventId]),
            returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i3.Stream<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> addEventComment(
    String? eventId,
    String? text,
    String? userId,
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addEventComment, [
              eventId,
              text,
              userId,
              userName,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteEventComments(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEventComments, [eventId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
