// Mocks generated by Mockito 5.4.6 from annotations
// in thunder/test/features/chat/data/repositories/chat_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:thunder/features/chat/data/datasources/chat_remote_data_source.dart'
    as _i4;
import 'package:thunder/models/chat_model.dart' as _i2;
import 'package:thunder/models/message_model.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatModel_0 extends _i1.SmartFake implements _i2.ChatModel {
  _FakeChatModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageModel_1 extends _i1.SmartFake implements _i3.MessageModel {
  _FakeMessageModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRemoteDataSource extends _i1.Mock
    implements _i4.ChatRemoteDataSource {
  MockChatRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getChatId(String? userA, String? userB) =>
      (super.noSuchMethod(
            Invocation.method(#getChatId, [userA, userB]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getChatId, [userA, userB]),
            ),
          )
          as String);

  @override
  _i6.Future<_i2.ChatModel> getOrCreatePrivateChat(
    String? userA,
    String? userB,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreatePrivateChat, [userA, userB]),
            returnValue: _i6.Future<_i2.ChatModel>.value(
              _FakeChatModel_0(
                this,
                Invocation.method(#getOrCreatePrivateChat, [userA, userB]),
              ),
            ),
          )
          as _i6.Future<_i2.ChatModel>);

  @override
  _i6.Future<_i2.ChatModel> createGroupChat({
    required String? name,
    required String? createdBy,
    required List<String>? participants,
    String? description,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGroupChat, [], {
              #name: name,
              #createdBy: createdBy,
              #participants: participants,
              #description: description,
              #photoUrl: photoUrl,
            }),
            returnValue: _i6.Future<_i2.ChatModel>.value(
              _FakeChatModel_0(
                this,
                Invocation.method(#createGroupChat, [], {
                  #name: name,
                  #createdBy: createdBy,
                  #participants: participants,
                  #description: description,
                  #photoUrl: photoUrl,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ChatModel>);

  @override
  _i6.Future<_i3.MessageModel> sendMessage({
    required String? chatId,
    required String? senderId,
    required String? senderName,
    String? senderPhotoUrl,
    String? text,
    _i3.MessageType? type = _i3.MessageType.text,
    String? imageUrl,
    String? videoUrl,
    String? audioUrl,
    String? fileUrl,
    String? fileName,
    int? fileSize,
    String? gifUrl,
    String? stickerUrl,
    Map<String, dynamic>? location,
    Map<String, dynamic>? contact,
    String? replyToMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatId: chatId,
              #senderId: senderId,
              #senderName: senderName,
              #senderPhotoUrl: senderPhotoUrl,
              #text: text,
              #type: type,
              #imageUrl: imageUrl,
              #videoUrl: videoUrl,
              #audioUrl: audioUrl,
              #fileUrl: fileUrl,
              #fileName: fileName,
              #fileSize: fileSize,
              #gifUrl: gifUrl,
              #stickerUrl: stickerUrl,
              #location: location,
              #contact: contact,
              #replyToMessageId: replyToMessageId,
            }),
            returnValue: _i6.Future<_i3.MessageModel>.value(
              _FakeMessageModel_1(
                this,
                Invocation.method(#sendMessage, [], {
                  #chatId: chatId,
                  #senderId: senderId,
                  #senderName: senderName,
                  #senderPhotoUrl: senderPhotoUrl,
                  #text: text,
                  #type: type,
                  #imageUrl: imageUrl,
                  #videoUrl: videoUrl,
                  #audioUrl: audioUrl,
                  #fileUrl: fileUrl,
                  #fileName: fileName,
                  #fileSize: fileSize,
                  #gifUrl: gifUrl,
                  #stickerUrl: stickerUrl,
                  #location: location,
                  #contact: contact,
                  #replyToMessageId: replyToMessageId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.MessageModel>);

  @override
  _i6.Stream<List<_i3.MessageModel>> getMessagesStream(
    String? chatId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesStream, [chatId], {#limit: limit}),
            returnValue: _i6.Stream<List<_i3.MessageModel>>.empty(),
          )
          as _i6.Stream<List<_i3.MessageModel>>);

  @override
  _i6.Future<List<_i3.MessageModel>> loadOlderMessages(
    String? chatId,
    DateTime? lastMessageTime, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadOlderMessages,
              [chatId, lastMessageTime],
              {#limit: limit},
            ),
            returnValue: _i6.Future<List<_i3.MessageModel>>.value(
              <_i3.MessageModel>[],
            ),
          )
          as _i6.Future<List<_i3.MessageModel>>);

  @override
  _i6.Stream<List<_i2.ChatModel>> getUserChats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserChats, [userId]),
            returnValue: _i6.Stream<List<_i2.ChatModel>>.empty(),
          )
          as _i6.Stream<List<_i2.ChatModel>>);

  @override
  _i6.Future<void> markMessageAsRead(String? messageId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageAsRead, [messageId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMessage(String? messageId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> editMessage(String? messageId, String? newText) =>
      (super.noSuchMethod(
            Invocation.method(#editMessage, [messageId, newText]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateTypingStatus(
    String? chatId,
    String? userId,
    bool? isTyping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTypingStatus, [chatId, userId, isTyping]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addReaction(
    String? messageId,
    String? userId,
    String? emoji,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addReaction, [messageId, userId, emoji]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeReaction(
    String? messageId,
    String? userId,
    String? emoji,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeReaction, [messageId, userId, emoji]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.MessageModel> sendVoiceMessage({
    required String? chatId,
    required String? senderId,
    required String? senderName,
    String? senderPhotoUrl,
    required String? audioUrl,
    required Duration? duration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendVoiceMessage, [], {
              #chatId: chatId,
              #senderId: senderId,
              #senderName: senderName,
              #senderPhotoUrl: senderPhotoUrl,
              #audioUrl: audioUrl,
              #duration: duration,
            }),
            returnValue: _i6.Future<_i3.MessageModel>.value(
              _FakeMessageModel_1(
                this,
                Invocation.method(#sendVoiceMessage, [], {
                  #chatId: chatId,
                  #senderId: senderId,
                  #senderName: senderName,
                  #senderPhotoUrl: senderPhotoUrl,
                  #audioUrl: audioUrl,
                  #duration: duration,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.MessageModel>);

  @override
  _i6.Future<_i3.MessageModel> sendFileMessage({
    required String? chatId,
    required String? senderId,
    required String? senderName,
    String? senderPhotoUrl,
    required String? fileUrl,
    required String? fileName,
    required int? fileSize,
    String? fileExtension,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendFileMessage, [], {
              #chatId: chatId,
              #senderId: senderId,
              #senderName: senderName,
              #senderPhotoUrl: senderPhotoUrl,
              #fileUrl: fileUrl,
              #fileName: fileName,
              #fileSize: fileSize,
              #fileExtension: fileExtension,
            }),
            returnValue: _i6.Future<_i3.MessageModel>.value(
              _FakeMessageModel_1(
                this,
                Invocation.method(#sendFileMessage, [], {
                  #chatId: chatId,
                  #senderId: senderId,
                  #senderName: senderName,
                  #senderPhotoUrl: senderPhotoUrl,
                  #fileUrl: fileUrl,
                  #fileName: fileName,
                  #fileSize: fileSize,
                  #fileExtension: fileExtension,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.MessageModel>);

  @override
  _i6.Future<_i3.MessageModel> forwardMessage({
    required _i3.MessageModel? originalMessage,
    required String? targetChatId,
    required String? senderId,
    required String? senderName,
    String? senderPhotoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forwardMessage, [], {
              #originalMessage: originalMessage,
              #targetChatId: targetChatId,
              #senderId: senderId,
              #senderName: senderName,
              #senderPhotoUrl: senderPhotoUrl,
            }),
            returnValue: _i6.Future<_i3.MessageModel>.value(
              _FakeMessageModel_1(
                this,
                Invocation.method(#forwardMessage, [], {
                  #originalMessage: originalMessage,
                  #targetChatId: targetChatId,
                  #senderId: senderId,
                  #senderName: senderName,
                  #senderPhotoUrl: senderPhotoUrl,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.MessageModel>);

  @override
  _i6.Future<List<_i3.MessageModel>> searchMessages(
    String? chatId,
    String? query, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchMessages,
              [chatId, query],
              {#limit: limit},
            ),
            returnValue: _i6.Future<List<_i3.MessageModel>>.value(
              <_i3.MessageModel>[],
            ),
          )
          as _i6.Future<List<_i3.MessageModel>>);

  @override
  _i6.Future<List<_i3.MessageModel>> searchAllMessages(
    String? userId,
    String? query, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchAllMessages,
              [userId, query],
              {#limit: limit},
            ),
            returnValue: _i6.Future<List<_i3.MessageModel>>.value(
              <_i3.MessageModel>[],
            ),
          )
          as _i6.Future<List<_i3.MessageModel>>);
}
