// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ0Qdn4R76e1KkYt9zyBEwjC9pYjHw2d0',
    appId: '1:546545603716:web:eb9eee4dcbe8b78daf9ed1',
    messagingSenderId: '546545603716',
    projectId: 'thunder-52d2e',
    authDomain: 'thunder-52d2e.firebaseapp.com',
    storageBucket: 'thunder-52d2e.firebasestorage.app',
    measurementId: 'G-552EFPR43N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHyNRbvg9Yqps7ZeeeqrGbmo2l4jfOYAo',
    appId: '1:546545603716:android:eb3b03ba53e75fa8af9ed1',
    messagingSenderId: '546545603716',
    projectId: 'thunder-52d2e',
    storageBucket: 'thunder-52d2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLo3qijXKGPJSXTUWlaF7EUZL0i4AsuT8',
    appId: '1:546545603716:ios:e082bb0af2c0f025af9ed1',
    messagingSenderId: '546545603716',
    projectId: 'thunder-52d2e',
    storageBucket: 'thunder-52d2e.firebasestorage.app',
    iosBundleId: 'com.example.thunder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLo3qijXKGPJSXTUWlaF7EUZL0i4AsuT8',
    appId: '1:546545603716:ios:e082bb0af2c0f025af9ed1',
    messagingSenderId: '546545603716',
    projectId: 'thunder-52d2e',
    storageBucket: 'thunder-52d2e.firebasestorage.app',
    iosBundleId: 'com.example.thunder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ0Qdn4R76e1KkYt9zyBEwjC9pYjHw2d0',
    appId: '1:546545603716:web:96c666b60d8b789faf9ed1',
    messagingSenderId: '546545603716',
    projectId: 'thunder-52d2e',
    authDomain: 'thunder-52d2e.firebaseapp.com',
    storageBucket: 'thunder-52d2e.firebasestorage.app',
    measurementId: 'G-ETHZ78SCDE',
  );
}
