// Mocks generated by Mockito 5.4.6 from annotations
// in thunder/test/features/event/domain/usecases/add_event_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:thunder/core/errors/failures.dart' as _i2;
import 'package:thunder/features/event/domain/repositories/event_repository.dart'
    as _i3;
import 'package:thunder/models/event_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i3.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> addEvent(_i5.EventModel? event) =>
      (super.noSuchMethod(
            Invocation.method(#addEvent, [event]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#addEvent, [event]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Stream<List<_i5.EventModel>> getEventsStream() =>
      (super.noSuchMethod(
            Invocation.method(#getEventsStream, []),
            returnValue: _i4.Stream<List<_i5.EventModel>>.empty(),
          )
          as _i4.Stream<List<_i5.EventModel>>);

  @override
  _i4.Stream<List<_i5.EventModel>> getUserEventsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserEventsStream, [userId]),
            returnValue: _i4.Stream<List<_i5.EventModel>>.empty(),
          )
          as _i4.Stream<List<_i5.EventModel>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, List<_i5.EventModel>>> fetchNextEvents({
    DateTime? startAfter,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNextEvents, [], {
              #startAfter: startAfter,
              #limit: limit,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i2.Failure, List<_i5.EventModel>>>.value(
                  _FakeEither_0<_i2.Failure, List<_i5.EventModel>>(
                    this,
                    Invocation.method(#fetchNextEvents, [], {
                      #startAfter: startAfter,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, List<_i5.EventModel>>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> updateEvent(
    _i5.EventModel? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvent, [event]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#updateEvent, [event]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> deleteEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [eventId]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#deleteEvent, [eventId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> joinEvent(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#joinEvent, [eventId, userId]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#joinEvent, [eventId, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> leaveEvent(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#leaveEvent, [eventId, userId]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#leaveEvent, [eventId, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> sendJoinRequest(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendJoinRequest, [eventId, userId]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#sendJoinRequest, [eventId, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> approveJoinRequest(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#approveJoinRequest, [eventId, userId]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#approveJoinRequest, [eventId, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> rejectJoinRequest(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rejectJoinRequest, [eventId, userId]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#rejectJoinRequest, [eventId, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> cancelJoinRequest(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cancelJoinRequest, [eventId, userId]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#cancelJoinRequest, [eventId, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);
}
